### ISSUE TITLE
this.wave.attr(...).transiton is not a function

### ISSUE THREAD

**Issue by tinaClin** [trendmicro-frontend/react-liquid-gauge#1]
We used "d3-selection": "~1.0.2" module in our product, and occur javascript error "this.wave.attr(...).transition is not a function". The workaround is product uses the same version of d3-selection module as one in "react-liquid-gauge" component.

**Comment by cheton** [comment]
Related issues:
* https://github.com/d3/d3-transition/issues/57
* https://github.com/d3/d3/issues/2850#issuecomment-234815190
* https://github.com/d3/d3/issues/2940#issuecomment-239204495

Importing the top-line d3 package resolved the problem.

**Comment by kidsit** [comment]
@cheton , what do you mean "Importing the top-line d3 package resolve the problem"? I found the similar issue, but i have not found out a solution for it. Thanks~

**Comment by cheton** [comment]
Here is the fix to workaround this issue: https://github.com/trendmicro-frontend/react-liquid-gauge/commit/fbe63c5c7cf0012b719ee4131d8b6c03a123b421

**Comment by kidsit** [comment]
thanks cheton
