### ISSUE TITLE
Why not support react@16.5.x?

### ISSUE THREAD

**Issue by Jungwoo-An** [trendmicro-frontend/react-liquid-gauge#4]

**Comment by cheton** [comment]
@Jungwoo-An 

I don't see any issues for supporting React 16.5.x. Please describe your problem in details. Thanks.

**Comment by Jungwoo-An** [comment]
@cheton Oh, sorry. i mistake.

This issue occurred when using react-dom@16.5.2 with profiler, cause is use `'react-dom': 'react-dom/profiling'` in resolve.alias of webpack
